name: CI/CD Build Tests

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['18', '20', '22']
    name: ${{ matrix.os }} - Node ${{ matrix.node }} Test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Set up Node
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Install Dependencies
      run: yarn
    - name: Execute Unit Tests
      env:
        AMI_HOST: ${{ secrets.AMI_HOST }}
        AMI_USERNAME: ${{ secrets.AMI_USERNAME }}
        AMI_PASSWORD: ${{ secrets.AMI_PASSWORD }}
      run: yarn test
    - name: Publish to NPM
      if: matrix.node == '18' && matrix.os == 'ubuntu-latest' && github.event_name == 'release'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public
